#---
#apiVersion: v1
#kind: Service
#metadata:
##  annotations:
##    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "udp"
##    service.beta.kubernetes.io/aws-load-balancer-type: nlb
#  labels:
#    io.kompose.service: node
#  name: node
#spec:
##  type: LoadBalancer
#  ports:
#  - name: "30303"
#    port: 30303
#    protocol: UDP
#    targetPort: 30303
#  selector:
#    io.kompose.service: node
